services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - server_network

  database:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server_network

volumes:
  postgres_data:


networks:
  server_network:
    driver: bridge
